//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3268 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.09 at 03:48:28 ���� CST 
//


package com.hp.sdf.ngp.handmark.model;

import java.math.BigDecimal;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hp.sdf.ngp.handmark package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Country_QNAME = new QName("http://www.handmark.com/DataTypes", "country");
    private final static QName _Developer_QNAME = new QName("http://www.handmark.com/master_browse_response", "developer");
    private final static QName _Value_QNAME = new QName("http://www.handmark.com/DataTypes", "value");
    private final static QName _CatalogId_QNAME = new QName("http://www.handmark.com/master_browse_response", "catalog_id");
    private final static QName _ProductId_QNAME = new QName("http://www.handmark.com/master_browse_response", "product_id");
    private final static QName _ProdPrice_QNAME = new QName("http://www.handmark.com/DataTypes", "prod_price");
    private final static QName _Category_QNAME = new QName("http://www.handmark.com/DataTypes", "category");
    private final static QName _VersionLastUpdated_QNAME = new QName("http://www.handmark.com/master_browse_response", "version_last_updated");
    private final static QName _Version_QNAME = new QName("http://www.handmark.com/master_browse_response", "version");
    private final static QName _CategoryId_QNAME = new QName("http://www.handmark.com/master_browse_response", "category_id");
    private final static QName _PrimaryImage_QNAME = new QName("http://www.handmark.com/master_browse_response", "primary_image");
    private final static QName _CatalogName_QNAME = new QName("http://www.handmark.com/master_browse_response", "catalog_name");
    private final static QName _Currency_QNAME = new QName("http://www.handmark.com/DataTypes", "currency");
    private final static QName _Device_QNAME = new QName("http://www.handmark.com/DataTypes", "device");
    private final static QName _Language_QNAME = new QName("http://www.handmark.com/DataTypes", "language");
    private final static QName _Image_QNAME = new QName("http://www.handmark.com/master_browse_response", "image");
    private final static QName _Rating_QNAME = new QName("http://www.handmark.com/master_browse_response", "rating");
    private final static QName _RequiresEmail_QNAME = new QName("http://www.handmark.com/master_browse_response", "requires_email");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hp.sdf.ngp.handmark
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Prices }
     * 
     */
    public Prices createPrices() {
        return new Prices();
    }

    /**
     * Create an instance of {@link Countries }
     * 
     */
    public Countries createCountries() {
        return new Countries();
    }

    /**
     * Create an instance of {@link DisplayName }
     * 
     */
    public DisplayName createDisplayName() {
        return new DisplayName();
    }

    /**
     * Create an instance of {@link FullDescription }
     * 
     */
    public FullDescription createFullDescription() {
        return new FullDescription();
    }

    /**
     * Create an instance of {@link Devices }
     * 
     */
    public Devices createDevices() {
        return new Devices();
    }

    /**
     * Create an instance of {@link Catalog }
     * 
     */
    public Catalog createCatalog() {
        return new Catalog();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link Categories }
     * 
     */
    public Categories createCategories() {
        return new Categories();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Products }
     * 
     */
    public Products createProducts() {
        return new Products();
    }

    /**
     * Create an instance of {@link SubCategories }
     * 
     */
    public SubCategories createSubCategories() {
        return new SubCategories();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/DataTypes", name = "country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/master_browse_response", name = "developer")
    public JAXBElement<String> createDeveloper(String value) {
        return new JAXBElement<String>(_Developer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/DataTypes", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/master_browse_response", name = "catalog_id")
    public JAXBElement<Byte> createCatalogId(Byte value) {
        return new JAXBElement<Byte>(_CatalogId_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/master_browse_response", name = "product_id")
    public JAXBElement<Integer> createProductId(Integer value) {
        return new JAXBElement<Integer>(_ProductId_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/DataTypes", name = "prod_price")
    public JAXBElement<BigDecimal> createProdPrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ProdPrice_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/DataTypes", name = "category")
    public JAXBElement<Short> createCategory(Short value) {
        return new JAXBElement<Short>(_Category_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/master_browse_response", name = "version_last_updated")
    public JAXBElement<XMLGregorianCalendar> createVersionLastUpdated(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_VersionLastUpdated_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/master_browse_response", name = "version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/master_browse_response", name = "category_id")
    public JAXBElement<Short> createCategoryId(Short value) {
        return new JAXBElement<Short>(_CategoryId_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/master_browse_response", name = "primary_image")
    public JAXBElement<String> createPrimaryImage(String value) {
        return new JAXBElement<String>(_PrimaryImage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/master_browse_response", name = "catalog_name")
    public JAXBElement<String> createCatalogName(String value) {
        return new JAXBElement<String>(_CatalogName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/DataTypes", name = "currency")
    public JAXBElement<String> createCurrency(String value) {
        return new JAXBElement<String>(_Currency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/DataTypes", name = "device")
    public JAXBElement<Short> createDevice(Short value) {
        return new JAXBElement<Short>(_Device_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/DataTypes", name = "language")
    public JAXBElement<String> createLanguage(String value) {
        return new JAXBElement<String>(_Language_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/master_browse_response", name = "image")
    public JAXBElement<String> createImage(String value) {
        return new JAXBElement<String>(_Image_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/master_browse_response", name = "rating")
    public JAXBElement<Byte> createRating(Byte value) {
        return new JAXBElement<Byte>(_Rating_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.handmark.com/master_browse_response", name = "requires_email")
    public JAXBElement<Boolean> createRequiresEmail(Boolean value) {
        return new JAXBElement<Boolean>(_RequiresEmail_QNAME, Boolean.class, null, value);
    }

}
