//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3268 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.09 at 03:48:28 ���� CST 
//


package com.hp.sdf.ngp.handmark.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for product element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="product">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{http://www.handmark.com/master_browse_response}product_id"/>
 *           &lt;element ref="{http://www.handmark.com/master_browse_response}image"/>
 *           &lt;element ref="{http://www.handmark.com/master_browse_response}primary_image"/>
 *           &lt;element ref="{http://www.handmark.com/master_browse_response}display_name" maxOccurs="unbounded"/>
 *           &lt;element ref="{http://www.handmark.com/master_browse_response}description" maxOccurs="unbounded"/>
 *           &lt;element ref="{http://www.handmark.com/master_browse_response}full_description" maxOccurs="unbounded"/>
 *           &lt;element ref="{http://www.handmark.com/master_browse_response}prices" maxOccurs="unbounded"/>
 *           &lt;element ref="{http://www.handmark.com/master_browse_response}developer"/>
 *           &lt;element ref="{http://www.handmark.com/master_browse_response}version"/>
 *           &lt;element ref="{http://www.handmark.com/master_browse_response}version_last_updated"/>
 *           &lt;element ref="{http://www.handmark.com/master_browse_response}rating"/>
 *           &lt;element ref="{http://www.handmark.com/master_browse_response}requires_email"/>
 *           &lt;element ref="{http://www.handmark.com/master_browse_response}devices"/>
 *           &lt;element ref="{http://www.handmark.com/master_browse_response}countries"/>
 *           &lt;element ref="{http://www.handmark.com/master_browse_response}categories"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productId",
    "image",
    "primaryImage",
    "displayName",
    "description",
    "fullDescription",
    "prices",
    "developer",
    "version",
    "versionLastUpdated",
    "rating",
    "requiresEmail",
    "devices",
    "countries",
    "categories"
})
@XmlRootElement(name = "product")
public class Product {

    @XmlElement(name = "product_id", namespace = "http://www.handmark.com/master_browse_response")
    protected int productId;
    @XmlElement(namespace = "http://www.handmark.com/master_browse_response", required = true)
    protected String image;
    @XmlElement(name = "primary_image", namespace = "http://www.handmark.com/master_browse_response", required = true)
    protected String primaryImage;
    @XmlElement(name = "display_name", namespace = "http://www.handmark.com/master_browse_response", required = true)
    protected List<DisplayName> displayName;
    @XmlElement(namespace = "http://www.handmark.com/master_browse_response", required = true)
    protected List<Description> description;
    @XmlElement(name = "full_description", namespace = "http://www.handmark.com/master_browse_response", required = true)
    protected List<FullDescription> fullDescription;
    @XmlElement(namespace = "http://www.handmark.com/master_browse_response", required = true)
    protected List<Prices> prices;
    @XmlElement(namespace = "http://www.handmark.com/master_browse_response", required = true)
    protected String developer;
    @XmlElement(namespace = "http://www.handmark.com/master_browse_response", required = true)
    protected String version;
    @XmlElement(name = "version_last_updated", namespace = "http://www.handmark.com/master_browse_response", required = true)
    protected XMLGregorianCalendar versionLastUpdated;
    @XmlElement(namespace = "http://www.handmark.com/master_browse_response")
    protected byte rating;
    @XmlElement(name = "requires_email", namespace = "http://www.handmark.com/master_browse_response")
    protected boolean requiresEmail;
    @XmlElement(namespace = "http://www.handmark.com/master_browse_response", required = true)
    protected Devices devices;
    @XmlElement(namespace = "http://www.handmark.com/master_browse_response", required = true)
    protected Countries countries;
    @XmlElement(namespace = "http://www.handmark.com/master_browse_response", required = true)
    protected Categories categories;

    /**
     * Gets the value of the productId property.
     * 
     */
    public int getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     */
    public void setProductId(int value) {
        this.productId = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the primaryImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryImage() {
        return primaryImage;
    }

    /**
     * Sets the value of the primaryImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryImage(String value) {
        this.primaryImage = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisplayName }
     * 
     * 
     */
    public List<DisplayName> getDisplayName() {
        if (displayName == null) {
            displayName = new ArrayList<DisplayName>();
        }
        return this.displayName;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Description }
     * 
     * 
     */
    public List<Description> getDescription() {
        if (description == null) {
            description = new ArrayList<Description>();
        }
        return this.description;
    }

    /**
     * Gets the value of the fullDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fullDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFullDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FullDescription }
     * 
     * 
     */
    public List<FullDescription> getFullDescription() {
        if (fullDescription == null) {
            fullDescription = new ArrayList<FullDescription>();
        }
        return this.fullDescription;
    }

    /**
     * Gets the value of the prices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Prices }
     * 
     * 
     */
    public List<Prices> getPrices() {
        if (prices == null) {
            prices = new ArrayList<Prices>();
        }
        return this.prices;
    }

    /**
     * Gets the value of the developer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeveloper() {
        return developer;
    }

    /**
     * Sets the value of the developer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeveloper(String value) {
        this.developer = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the versionLastUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVersionLastUpdated() {
        return versionLastUpdated;
    }

    /**
     * Sets the value of the versionLastUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVersionLastUpdated(XMLGregorianCalendar value) {
        this.versionLastUpdated = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     */
    public byte getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     */
    public void setRating(byte value) {
        this.rating = value;
    }

    /**
     * Gets the value of the requiresEmail property.
     * 
     */
    public boolean isRequiresEmail() {
        return requiresEmail;
    }

    /**
     * Sets the value of the requiresEmail property.
     * 
     */
    public void setRequiresEmail(boolean value) {
        this.requiresEmail = value;
    }

    /**
     * Gets the value of the devices property.
     * 
     * @return
     *     possible object is
     *     {@link Devices }
     *     
     */
    public Devices getDevices() {
        return devices;
    }

    /**
     * Sets the value of the devices property.
     * 
     * @param value
     *     allowed object is
     *     {@link Devices }
     *     
     */
    public void setDevices(Devices value) {
        this.devices = value;
    }

    /**
     * Gets the value of the countries property.
     * 
     * @return
     *     possible object is
     *     {@link Countries }
     *     
     */
    public Countries getCountries() {
        return countries;
    }

    /**
     * Sets the value of the countries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Countries }
     *     
     */
    public void setCountries(Countries value) {
        this.countries = value;
    }

    /**
     * Gets the value of the categories property.
     * 
     * @return
     *     possible object is
     *     {@link Categories }
     *     
     */
    public Categories getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Categories }
     *     
     */
    public void setCategories(Categories value) {
        this.categories = value;
    }

}
