--Please create database and table space before execute this sql.
--Table Space (STOREFRONT)

--Create user STOREFRONT used by STOREFRONT tables
--is used for application
CREATE USER "STOREFRONT"  PROFILE "DEFAULT" 
    IDENTIFIED BY "STOREFRONT" DEFAULT TABLESPACE "STOREFRONT" 
    ACCOUNT UNLOCK;
GRANT "CONNECT" TO "STOREFRONT";
GRANT "RESOURCE" TO "STOREFRONT";

COMMIT;

--Table Space (JBOSSPORTAL)

--Create user JBOSSPORTAL used by JBOSS Portal tables
CREATE USER "JBOSSPORTAL"  PROFILE "DEFAULT" 
    IDENTIFIED BY "JBOSSPORTAL" DEFAULT TABLESPACE "STOREFRONT" 
    ACCOUNT UNLOCK;
GRANT "CONNECT" TO "JBOSSPORTAL";
GRANT "RESOURCE" TO "JBOSSPORTAL";

COMMIT;

-- $Id: user.sql 3480 2008-08-21 02:42:12Z wezhang $